function age_of_trinity(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Bb='&',fc='.cache.html',$='/',Yb='20CB83D46624AF48DD4D685648CBCAC3',_b='9E8C715A77F55ED7071AB4B022528F7C',ec=':',Zb=':1',$b=':2',nb='::',nc='<script defer="defer">age_of_trinity.onInjectionDone(\'age_of_trinity\')<\/script>',gb='<script id="',qb='=',Z='?',ac='B63529CCE9FAB73301E682AD35A0ABCC',bc='BECC942369AFD368F6ECDA1136EF0849',sb='Bad handler "',cc='D952710BA649FF78FD73053CD2D03324',mc='DOMContentLoaded',dc='EC5073C3BE54E6780AA7B08DF910B8A1',ib='SCRIPT',fb='__gwt_marker_age_of_trinity',P='age_of_trinity',db='age_of_trinity.nocache.js',mb='age_of_trinity::',Ib='android',jb='base',bb='baseUrl',S='begin',R='bootstrap',ab='clear.cache.gif',pb='content',Jb='desktop',X='end',Ab='formfactor',Sb='gecko',Tb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',gc='gwt/clean/clean.css',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',lc='head',Wb='hosted.html?age_of_trinity',kc='href',Rb='ie6',Qb='ie8',Pb='ie9',wb='iframe',_='img',Gb='ipad',Cb='iphone',Db='ipod',xb="javascript:''",hc='link',Vb='loadExternalRefs',kb='meta',Fb='mobile',zb='moduleRequested',W='moduleStartup',Ob='msie',lb='name',Lb='opera',yb='position:absolute;width:0;height:0;border:none',ic='rel',Nb='safari',cb='script',Xb='selectingPermutation',Q='startup',jc='stylesheet',Hb='tablet',eb='undefined',Ub='unknown',Kb='user.agent',Mb='webkit',Eb='windows phone';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}age_of_trinity=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var a=location.search;var b=a.indexOf(Ab);if(b>=0){var c=a.substring(b);var d=c.indexOf(qb)+1;var e=c.indexOf(Bb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Cb)!=-1||(f.indexOf(Db)!=-1||f.indexOf(Eb)!=-1)){return Fb}else if(f.indexOf(Gb)!=-1){return Hb}else if(f.indexOf(Ib)!=-1||f.indexOf(Fb)!=-1){var g=160;var h=l.screen.width/g;var i=l.screen.height/g;var j=Math.sqrt(h*h+i*i);return j<6?Fb:Hb}return Jb};u[Ab]={desktop:0,mobile:1,tablet:2};v[Kb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Lb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1&&m.documentMode>=9}())return Pb;if(function(){return b.indexOf(Ob)!=-1&&m.documentMode>=8}())return Qb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;return Ub};u[Kb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};age_of_trinity.onScriptLoad=function(){if(H){q=true;B()}};age_of_trinity.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Vb,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=Wb;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Xb});if(!A()){try{F([Jb,Rb],Yb);F([Fb,Rb],Yb+Zb);F([Hb,Rb],Yb+$b);F([Jb,Tb],_b);F([Fb,Tb],_b+Zb);F([Hb,Tb],_b+$b);F([Jb,Lb],ac);F([Fb,Lb],ac+Zb);F([Hb,Lb],ac+$b);F([Jb,Qb],bc);F([Fb,Qb],bc+Zb);F([Hb,Qb],bc+$b);F([Jb,Pb],cc);F([Fb,Pb],cc+Zb);F([Hb,Pb],cc+$b);F([Jb,Nb],dc);F([Fb,Nb],dc+Zb);F([Hb,Nb],dc+$b);J=w[G(Ab)][G(Kb)];var L=J.indexOf(ec);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+fc}catch(a){return}}var M;function N(){if(!r){r=true;if(!__gwt_stylesLoaded[gc]){var a=m.createElement(hc);__gwt_stylesLoaded[gc]=a;a.setAttribute(ic,jc);a.setAttribute(kc,s+gc);m.getElementsByTagName(lc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(mc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(mc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:Vb,millis:(new Date).getTime(),type:S});m.write(nc)}
age_of_trinity();